title: Where's My Chips?
markdown: kramdown

# for atom feed
author:
  name: Paul Kerrigan
  email: pauljameskerrigan+site@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:year/:month/:day/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
